### ISSUE TITLE
help with the installation

### ISSUE THREAD

**Issue by mshakya** [solomonik/jaccard-ctf#1]
Hi, I am trying to install this tool, but not able to. I followed the instruction in README that says to use `./configure --no-dynamic && make`, but there is no ./configure file. Please advise. Thank you.

**Comment by raghavendrak** [comment]
This tool uses Cyclops Tensor Framework (CTF) routines. CTF is a distributed memory library that delivers routines for contraction and summation of sparse and dense tensors.

Download and build CTF: https://github.com/cyclops-community/ctf.

Easiest way to do above is to install CTF with `./configure --no-dynamic && make`; install globally with sudo make install, but local build would also work fine.

Once CTF is installed, to compile this tool provide include and lib path to CTF in config.mk and run make.

README updated. Thank you.

**Comment by mshakya** [comment]
Thank you. Will check it out.
